title: Chief
author: Randy E. Oyarzabal
author_email: github@randyoyarzabal.com
url: https://chief.reonetlabs.us
show_downloads: true
enable_copy_code_button: true
toc: true
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme 
categories: [bash, git, openshift, kubernetes, linux, vault, command-line]
tags: [bash, git, openshift, kubernetes, linux, command-line, open-source]