remote_theme: pages-themes/leap-day
plugins:
  - jekyll-remote-theme
  - jekyll-sass
  - jekyll-seo-tag
  
title: Chief
author: Randy E. Oyarzabal
author_email: github@randyoyarzabal.com
url: https://chief.reonetlabs.us
show_downloads: false
enable_copy_code_button: true
toc: true
categories: [bash, git, openshift, kubernetes, linux, vault, command-line]
tags: [bash, git, openshift, kubernetes, linux, command-line, open-source]
