title: Chief
author: Randy E. Oyarzabal
author_email: github@randyoyarzabal.com
url: https://chief.reonetlabs.us
show_downloads: true
enable_copy_code_button: true
toc: true
categories: [bash, git, openshift, kubernetes, linux, command-line]
tags: [bash, git, openshift, kubernetes, linux, command-line, open-source]
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

defaults:
  - scope:
      path: ""
    values:
      layout: default
      assets:
        js:
          - assets/js/copyCode.js
