title: Chief
tagline: [Get your BASH functions and aliases in order]
description: [Chief is BASH library system with extra features such as prompt and RSA keys management. It allows you to quickly create, manage, and share environment variables, aliases and functions to be used personally or in a team environment.]
author: Randy E. Oyarzabal
author_email: github@randyoyarzabal.com
url: https://chief.reonetlabs.us
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have oneshow_downloads: true
toc: true
overflow-x: scroll
categories: [bash, git, openshift, kubernetes, linux, command-line]
tags: [bash, git, openshift, kubernetes, linux, command-line, open-source]