title: Chief
description: Bash Plugin Manager & Terminal Enhancement Tool
author: Randy E. Oyarzabal
author_email: github@randyoyarzabal.com
url: https://chief.reonetlabs.us
baseurl: ""

# Just the Docs theme - perfect for documentation sites
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Site settings
logo: ""
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Heading anchor links appear on hover over h1-h6 tags in page content
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2024 Randy E. Oyarzabal. Distributed under the MIT License."

# Footer last modified
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Custom copy button
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

plugins:
- jekyll-remote-theme 
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections for organizing content
collections:
  guides:
    permalink: /:collection/:name/
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile

categories: [bash, git, openshift, kubernetes, linux, vault, command-line]
tags: [bash, git, openshift, kubernetes, linux, command-line, open-source]