title: Chief
tagline: [Get your BASH functions and aliases in order]
show_downloads: false
author: Randy E. Oyarzabal
author_email: github@randyoyarzabal.com
url: https://chief.reonetlabs.us
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
toc: true
overflow-x: scroll
categories: [bash, git, openshift, kubernetes, linux, command-line]
tags: [bash, git, openshift, kubernetes, linux, command-line, open-source]
