title: Chief
tagline: Get your BASH together!
author: Randy E. Oyarzabal
author_email: github@randyoyarzabal.com
url: https://chief.reonetlabs.us
show_downloads: true
enable_copy_code_button: true
categories: [bash, git, openshift, kubernetes, linux, command-line]
tags: [bash, git, openshift, kubernetes, linux, command-line, open-source]
theme: jekyll-theme-leap-day

sass:
  sass_dir: _sass
  style: compressed

collections:
  # Enable collections if needed for organizing code blocks
  code-blocks:
    output: true

defaults:
  - scope:
      path: "" # applies to all files
    values:
      layout: default
      assets:
        js:
          - copyCode.js
        css:
          - style.scss

include:
  - _includes
  - assets/js
  - assets/css

exclude:
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock